remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
author: s_lity
title: REV
description: _REV BL0G

collections_dir: content
collections:
  events:
    output: true
  projects:
    output: true